/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package introduccion

object App {
  def main(args: Array[String]): Unit = {
    val ob1 = new ListaFactoriales()
    val list_total: List[BigInt] = ob1.objListaFactoriales(10)
    print(list_total.reverse)
  }

  def greeting(): String = "Hello, world!"
}
