/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package introduccion

object App {
  def main(args: Array[String]): Unit = {
    val objEjercicioListas: EjercicioListas = new EjercicioListas()
    print(objEjercicioListas.repetirListas(List(1,2,3),1))
  }

  def greeting(): String = "Hello, world!"
}
