/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package introduccion

object App {
  def main(args: Array[String]): Unit = {
    val objEjercicioListas: EjercicioListas = new EjercicioListas()
    print(objEjercicioListas.filtrarListas("igual",8,List(1,2,3,4,5,6,7,8,9,10)))
  }

  def greeting(): String = "Hello, world!"
}
